name: Auto-Login-Parsec

on: 
  workflow_dispatch:
    inputs:
      email:
        description: 'E-mail do Parsec'
        required: true
      password:
        description: 'Senha do Parsec'
        required: true

jobs:
  login-and-setup:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Parsec
      run: |
        choco install parsec -y --ignore-checksums

    - name: Add Parsec to PATH
      run: |
        $env:Path += ";C:\Program Files\Parsec"

    - name: Install Python Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Login Script
      run: |
        python scripts/parsec_login.py --email "${{ github.event.inputs.email }}" --password "${{ github.event.inputs.password }}"

    - name: Verify Login with Executable
      run: |
        "C:\Program Files\Parsec\Parsec.exe" --status

    - name: Verify Login with Shortcut
      run: |
        Start-Process -FilePath "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Parsec\Parsec.lnk" -ArgumentList "--status" -Wait

    - name: Keep Session Alive
      run: scripts/timeout.ps1
      
