name: Connect GitHub Runner to Parsec

on: 
  workflow_dispatch:
    inputs:
      email:
        description: 'E-mail do Parsec'
        required: true
      password:
        description: 'Senha do Parsec'
        required: true

jobs:
  connect-parsec:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Python Dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Parsec
      run: |
        choco install parsec -y --ignore-checksums

    - name: Launch Parsec and Login
      run: |
        python scripts/parsec_login.py --email "${{ github.event.inputs.email }}" --password "${{ github.event.inputs.password }}"

    - name: Keep Runner Active
      run: |
        $start = Get-Date
        while ((Get-Date) - $start).TotalSeconds -lt 3600 {
          Start-Sleep -Seconds 60
        }
        
